### ISSUE TITLE
Bug: macOS 14 Terminal rendering doesn't seem to work

### ISSUE THREAD

**Issue by joelparkerhenderson** [thomas-mauran/chess-tui#35] opened 2023-12-04 22:07 UTC
## macOS 14 Terminal rendering doesn't seem to work

macOS 14 Terminal rendering doesn't seem to work. See image.

<img width="811" alt="Screenshot 2023-12-04 at 5 05 27 PM" src="https://github.com/thomas-mauran/chess-tui/assets/27145/65919c5f-e826-4223-9f8b-b0ef52e17f3c">

**Comment by thomas-mauran** [comment] 2023-12-04 22:13
Hi, thanks for your feedback I tested on my Mac OS with warp and got no issue can you give more informations about your terminal, font and eventually themes !

**Comment by joelparkerhenderson** [comment] 2023-12-05 08:29
Good info thank you @jwodder. 

@thomas-mauran here's a suggestion for a way to do what you're asking about... you could add a command line option to launch with just black and white. And even better, a command line option such as '--debug' that prints whatever information you want to know about the setup.

Here's a screenshot with iTerm2 that shows the colors do work, but the pieces seem deformed:

<img width="643" alt="Screenshot 2023-12-05 at 3 26 03 AM" src="https://github.com/thomas-mauran/chess-tui/assets/27145/f5591fc0-e2eb-4d51-8396-9025d7c7adec">

**Comment by thomas-mauran** [comment] 2023-12-05 08:45
Great idea @joelparkerhenderson could be very useful, for the piece deformation it is because of the font size of the terminal, you can use ctrl or cmd + and - to adjust the size. If you need more informations about the commands of the game you can press h to open an help popup

**Comment by joelparkerhenderson** [comment] 2023-12-06 00:46
Is there a way to make the pieces render using their Unicode characters?

What I see in the existing source is a multiline pseudo graphic:
```rust
impl King {
    pub fn to_string() -> &'static str {
        "\
      ✚\n\
    ▞▀▄▀▚\n\
    ▙▄█▄▟\n\
    ▐███▌\n\
   ▗█████▖\n\
    "
```

My preference is to use Unicode, which scales well, and is especially good for TUIs in my experience, such as:

https://www.compart.com/en/unicode/U+265A

**Comment by joshka** [comment] 2023-12-06 11:31
The problem is those characters are only going to be a single cell. Which can look good (see https://github.com/nickzuber/chs), but this has a much bigger board.

**Comment by thomas-mauran** [comment] 2023-12-06 12:52
Yeah it might be better to keep the sprites for the board and the ascii for the move history

**Comment by joelparkerhenderson** [comment] 2023-12-07 14:59
I tried the zoom keys (cmd + and -) and they make the entire iTerm2 view bigger; the pieces continue to be deformed the same way in the same proportion to their squares.

@joshka Yes you're right and CHS is a good example of using the Unicode characters.

@thomas-mauran Thanks for the question about me doing a PR; I'm at capacity. If you make significant changes to the sprite approach, and you want me to take a look on my macOS, I'm happy to do that for you.

**Comment by thomas-mauran** [comment] 2023-12-09 19:43
Alright perfect, closing this issue I will ping you if I create a new one, thanks for your messages !

**Closed** 2023-12-09 19:43 UTC
Labels: bug

**Comment by joelparkerhenderson** [comment] 2023-12-12 04:42
Are you sure you want to close this bug? The bug still exists on current macOS, current default macOS Terminal app. There's an opportunity for you to have this bug open, so others can see it, and learn or contribute.
